# Generated by Django 3.0.8 on 2020-10-15 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('preprocessing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KMedoids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster', models.CharField(max_length=50)),
                ('rasio_k_p', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preprocessing.ProsesKDD')),
            ],
            options={
                'db_table': 'kmedoids',
            },
        ),
    ]
